### ISSUE TITLE
Create a Layout.js Module

### ISSUE THREAD

**Issue by fiannaca** [CSE512-15S/fp-fiannaca-sonyaa#2]
Responsibilities:
- This module should decide on the initial placement of nodes in the graph.
- This module should also provide methods to re-layout the nodes of a graph which a user has moved around.

Questions:
- Should we provide the user with the ability to specify how the nodes are initially placed? For instance, if the user adds a node (not connected to any other nodes yet), the new node could be placed to on any of the cardinal direction sides of the nodes already in the graph. We could allow the user to specify in their config file if they want it to be placed below, to the right, etc., by default.
- This layout module needs to respect the constraints of the size of the graph. Therefore, if the main area is full, should the layout engine be able to specify a zoom and translate for the entire graph to be able to dynamically fit all nodes on the screen? Or should we enable scrolling?

**Comment by sonyaa** [comment]
Did you have "user double-clicks, node is added automatically" in mind? I was thinking more along the lines of "user drags node to wherever they want on the screen", but I guess we want to support both. 

Personally, I would prefer scrolling, but we could support both. Let's start with whatever is easier (I assume scrolling).

**Comment by fiannaca** [comment]
Yeah, we should support both. The primary reason being that drag and drop is very inaccessible. For anyone not using a mouse, we have to have a well supported alternative.
